### ISSUE TITLE
カーソルのShift移動の弊害？

### ISSUE THREAD

**Issue by e-nakagawa** [kiyu12345/webkumihan#1]
ボックスを選択した状態で、素材の入力欄にてShift+矢印で範囲選択しようとするとボックスも同時に移動する

**Comment by kiyu12345** [comment]
ツールボックスにフォーカスがある場合は、Shift+矢印で選択範囲を移動しないようにしました。
また、ツールボックスにフォーカスがない場合、Delete または Backspace で素材を外すようにしました。（Shiftキーを押さなくてもOKにしました）
